# ----
# Site

title: DuckDuckGo Help Pages
url: "https://help.duckduckgo.com"
show_full_navigation: false
markdown: kramdown

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /logo.v109.svg
description: "DuckDuckGo Help Pages"
author:
    name: DuckDuckGo
    email:
    twitter: duckduckgo

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-menus

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENCE

collections:
    docs:
        title: Help Pages
        permalink: /:path/
        output: true

categories_order:
    - Company
    - How To Get DuckDuckGo
    - DuckDuckGo Search Results
    - DuckDuckGo Search Privacy
    - DuckDuckGo Web Browsing Privacy
    - DuckDuckGo Email Protection
    - DuckDuckGo App Tracking Protection
    - Misconceptions About DuckDuckGo
    - Legal

defaults:
    - scope:
          path: ""
      values:
          layout: default
          image: /logo.v109.svg
          description: DuckDuckGo is an independent internet privacy company that offers a private alternative to Google search & Chrome in one free app.
    - scope:
          path: ""
          type: "docs"
      values:
          seo:
              type: Article
          _comments:
              category: Group navigation links with this field
              order: Used to sort links in the navigation
          _options:
              content:
                  width: 800
                  height: 2000
